AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Album Lambda
Resources:
  Bucket1:
    Type: 'AWS::S3::Bucket'
  CDIndexLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: lambda_function_index
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./index-photos-copy
      Description: 'Lambda function for CD index photos'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::659573480588:role/admin_access'
      Environment:
        Variables:
          REGION: us-east-1
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated'
  CDSearchLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: lambda_function_search
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./search-photos-copy
      Description: 'Lambda function for CD search photos'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::659573480588:role/admin_access'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /search
            Method: get
      Environment:
        Variables:
          REGION: us-east-1
  
