AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: CD Demo Lambda
Resources:
  CDDemoLambda1:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: lambda_function_search
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./search-photos-copy
      Description: "Lambda function for CD Demo"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::659573480588:role/admin_access"
      Environment:
        Variables:
          REGION: us-east-1
  CDDemoLambda2:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: lambda_function_index
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./index-photos-copy
      Description: "Lambda function for CD Demo"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::659573480588:role/admin_access"
      Environment:
        Variables:
          REGION: us-east-1
